// Countries Database with Capitals and Flag Codes
// Flag images from: https://flagcdn.com

const COUNTRIES = [
    { name: "Afghanistan", capital: "Kabul", code: "af" },
    { name: "Albania", capital: "Tirana", code: "al" },
    { name: "Algeria", capital: "Algiers", code: "dz" },
    { name: "Argentina", capital: "Buenos Aires", code: "ar" },
    { name: "Australia", capital: "Canberra", code: "au" },
    { name: "Austria", capital: "Vienna", code: "at" },
    { name: "Bangladesh", capital: "Dhaka", code: "bd" },
    { name: "Belgium", capital: "Brussels", code: "be" },
    { name: "Bolivia", capital: "Sucre", code: "bo" },
    { name: "Brazil", capital: "Brasilia", code: "br" },
    { name: "Bulgaria", capital: "Sofia", code: "bg" },
    { name: "Cambodia", capital: "Phnom Penh", code: "kh" },
    { name: "Canada", capital: "Ottawa", code: "ca" },
    { name: "Chile", capital: "Santiago", code: "cl" },
    { name: "China", capital: "Beijing", code: "cn" },
    { name: "Colombia", capital: "Bogota", code: "co" },
    { name: "Croatia", capital: "Zagreb", code: "hr" },
    { name: "Cuba", capital: "Havana", code: "cu" },
    { name: "Cyprus", capital: "Nicosia", code: "cy" },
    { name: "Denmark", capital: "Copenhagen", code: "dk" },
    { name: "Ecuador", capital: "Quito", code: "ec" },
    { name: "Egypt", capital: "Cairo", code: "eg" },
    { name: "Estonia", capital: "Tallinn", code: "ee" },
    { name: "Ethiopia", capital: "Addis Ababa", code: "et" },
    { name: "Finland", capital: "Helsinki", code: "fi" },
    { name: "France", capital: "Paris", code: "fr" },
    { name: "Germany", capital: "Berlin", code: "de" },
    { name: "Ghana", capital: "Accra", code: "gh" },
    { name: "Greece", capital: "Athens", code: "gr" },
    { name: "Guatemala", capital: "Guatemala City", code: "gt" },
    { name: "Hungary", capital: "Budapest", code: "hu" },
    { name: "Iceland", capital: "Reykjavik", code: "is" },
    { name: "India", capital: "New Delhi", code: "in" },
    { name: "Indonesia", capital: "Jakarta", code: "id" },
    { name: "Iran", capital: "Tehran", code: "ir" },
    { name: "Iraq", capital: "Baghdad", code: "iq" },
    { name: "Ireland", capital: "Dublin", code: "ie" },
    { name: "Israel", capital: "Jerusalem", code: "il" },
    { name: "Italy", capital: "Rome", code: "it" },
    { name: "Jamaica", capital: "Kingston", code: "jm" },
    { name: "Japan", capital: "Tokyo", code: "jp" },
    { name: "Jordan", capital: "Amman", code: "jo" },
    { name: "Kenya", capital: "Nairobi", code: "ke" },
    { name: "Latvia", capital: "Riga", code: "lv" },
    { name: "Lebanon", capital: "Beirut", code: "lb" },
    { name: "Lithuania", capital: "Vilnius", code: "lt" },
    { name: "Malaysia", capital: "Kuala Lumpur", code: "my" },
    { name: "Mexico", capital: "Mexico City", code: "mx" },
    { name: "Mongolia", capital: "Ulaanbaatar", code: "mn" },
    { name: "Morocco", capital: "Rabat", code: "ma" },
    { name: "Nepal", capital: "Kathmandu", code: "np" },
    { name: "Netherlands", capital: "Amsterdam", code: "nl" },
    { name: "New Zealand", capital: "Wellington", code: "nz" },
    { name: "Nigeria", capital: "Abuja", code: "ng" },
    { name: "Norway", capital: "Oslo", code: "no" },
    { name: "Pakistan", capital: "Islamabad", code: "pk" },
    { name: "Panama", capital: "Panama City", code: "pa" },
    { name: "Paraguay", capital: "Asuncion", code: "py" },
    { name: "Peru", capital: "Lima", code: "pe" },
    { name: "Philippines", capital: "Manila", code: "ph" },
    { name: "Poland", capital: "Warsaw", code: "pl" },
    { name: "Portugal", capital: "Lisbon", code: "pt" },
    { name: "Romania", capital: "Bucharest", code: "ro" },
    { name: "Russia", capital: "Moscow", code: "ru" },
    { name: "Saudi Arabia", capital: "Riyadh", code: "sa" },
    { name: "Senegal", capital: "Dakar", code: "sn" },
    { name: "Serbia", capital: "Belgrade", code: "rs" },
    { name: "Singapore", capital: "Singapore", code: "sg" },
    { name: "Slovakia", capital: "Bratislava", code: "sk" },
    { name: "Slovenia", capital: "Ljubljana", code: "si" },
    { name: "South Africa", capital: "Pretoria", code: "za" },
    { name: "South Korea", capital: "Seoul", code: "kr" },
    { name: "Spain", capital: "Madrid", code: "es" },
    { name: "Sri Lanka", capital: "Colombo", code: "lk" },
    { name: "Sweden", capital: "Stockholm", code: "se" },
    { name: "Switzerland", capital: "Bern", code: "ch" },
    { name: "Taiwan", capital: "Taipei", code: "tw" },
    { name: "Tanzania", capital: "Dodoma", code: "tz" },
    { name: "Thailand", capital: "Bangkok", code: "th" },
    { name: "Tunisia", capital: "Tunis", code: "tn" },
    { name: "Turkey", capital: "Ankara", code: "tr" },
    { name: "Uganda", capital: "Kampala", code: "ug" },
    { name: "Ukraine", capital: "Kyiv", code: "ua" },
    { name: "United Kingdom", capital: "London", code: "gb" },
    { name: "United States", capital: "Washington D.C.", code: "us" },
    { name: "Uruguay", capital: "Montevideo", code: "uy" },
    { name: "Venezuela", capital: "Caracas", code: "ve" },
    { name: "Vietnam", capital: "Hanoi", code: "vn" },
    { name: "Zimbabwe", capital: "Harare", code: "zw" }
];

// Function to get flag URL from country code
function getFlagUrl(countryCode) {
    return `https://flagcdn.com/w320/${countryCode}.png`;
}
